name: GitHub Actions Build
run-name: Build java application then create docker image
on: [push]
jobs:
  Build-Java-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Build Java Application
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
      - run: mvn -B package -DskipTests
      - name: Build Docker Image
      - run: docker build -t my-docker-image .